name: First_workflow
on: workflow_dispatch
jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE CREDENTIALS }}
    - name: print greeting
      run: echo "Hello world"
    - name: bye greeting
      run: echo "bye"
